### ISSUE TITLE
User Research Questionnaire 

### ISSUE THREAD

**Issue by JacobLacouture** [alecdel/CurbAlert#9]
# [Google Form](https://docs.google.com/forms/d/1SpoiYGoZh1-542JbSL3AqUqzGI6c8E944a8vvdnAQIc/edit)

### [Multiple Choice] - How many times in the past month have you used services such as Facebook Marketplace or Offer Up in search of free items?

- 2 or less
- 2-4
- 4-6
- 6 or more

### [Multiple Choice] - How many times in the past year have you put things on the curb in hopes for someone to take it?

- 2 or less
- 2-4
- 4-6
- 6 or more

General Questions (for all users)
How did you hear about Curb Alert!?
a) Social media
b) Word of mouth
c) Online search
d) Other (please specify)

How often do you give away or pick up items from curbs?
a) Never
b) Rarely (a few times a year)
c) Occasionally (once a month)
d) Frequently (multiple times a month)

How important is it for you to have an easy-to-use app for posting/picking up curbside items?
a) Very important
b) Somewhat important
c) Not important

What features would be most important to you in an app like Curb Alert?
a) Easy posting of items
b) Ability to filter items by type
c) Accurate location services
d) Notifications when new items are available nearby

Persona-Specific Questions
Widow (recently lost a spouse)
Are you currently looking to downsize or clear out items after a significant life change?
a) Yes
b) No

Would you find it helpful to easily donate or give away items using Curb Alert! rather than traditional donation methods (e.g., charities, garage sales)?
a) Yes, it would simplify the process
b) No, I prefer traditional methods

What challenges do you face when trying to part with items that have sentimental value?
(Open-ended)

Hoarder (too much stuff)
Do you find it difficult to part with excess items, even though they are no longer useful to you?
a) Yes
b) No

Would a curbside app encourage you to declutter more regularly if you knew items were going to someone who could use them?
a) Yes
b) No

What kinds of incentives or reminders would help you stay motivated to declutter regularly?
a) Notifications/reminders
b) Seeing success stories of others
c) Earning rewards/points for giving items away
d) None of the above

Low-Income Individuals (benefit from free items)
How often do you look for free items (furniture, appliances, etc.) to help meet your needs?
a) Regularly
b) Occasionally
c) Rarely

What would make Curb Alert! valuable to you as someone who might benefit from free items?
a) Easy access to free items nearby
b) Reliable information about item condition
c) Quick alerts about new items available
d) All of the above

Do you have concerns about the quality or safety of items left on curbs?
a) Yes
b) No
c) Sometimes (please explain)

Family (moving in/out of a house)
Are you currently in the process of moving or planning to move in the near future?
a) Yes, within a few weeks
b) Yes, within a few months
c) No

Would you use Curb Alert! to help get rid of items you no longer need before a move?
a) Yes
b) No
c) Unsure

When moving, how likely are you to pick up free items to help furnish or prepare your new home?
a) Very likely
b) Somewhat likely
c) Unlikely

What types of items would you be most interested in picking up through Curb Alert! when moving?
a) Furniture
b) Appliances
c) Tools
d) Other (please specify)

Final Questions (for all users)
What other features or improvements would you like to see in Curb Alert! to make it more useful for you?
(Open-ended)

Would you be willing to recommend Curb Alert! to others?
a) Yes
b) No
c) Maybe

Any additional feedback or thoughts you'd like to share about the app?
(Open-ended)

**Comment by ryanmegna** [comment]
## Question Ideas

### [Multiple Choice] - How many times in the past month have you used services such as Facebook Marketplace or Offer Up in search of free items?

- 2 or less
- 2-4
- 4-6
- 6 or more

### [Multiple Choice] - How many times in the past year have you put things on the curb in hopes for someone to take it?

- 2 or less
- 2-4
- 4-6
- 6 or more
